name: API Automation with Allure

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  api-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Api-test

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v4

      # 2️⃣ Setup Java 17
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
       
      # 3️⃣ Setup Chrome
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v2.1.0

      # 4️⃣ Make gradlew executable
      - run: chmod +x ./gradlew

      # 5️⃣ Build project
      - name: Build with Gradle
        run: ./gradlew build

      # 6️⃣ Run API tests
      - name: Run API tests
        run: ./gradlew clean test --no-daemon

      # 7️⃣ Install Allure CLI
      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      # 8️⃣ Generate Allure report
      - name: Generate Allure Report
        run: allure generate build/allure-results -o build/reports/allure-report --clean

      # 9️⃣ Deploy report to GitHub Pages
      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: build/reports/allure-report
